services:
  starbucks_js:
    container_name: starbucks_js
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    env_file:
      - docker.env

  starbucks_js_redis:
    container_name: starbucks_js_redis
    image: "redis:alpine"
    restart: always
    env_file:
      - docker.env
    ports:
      - 6381:6379